[2023-02-13 22:27:01,010][tensorflow][WARNING] - AutoGraph could not transform <bound method GroupNormalization.call of <tensorflow_addons.layers.normalizations.GroupNormalization object at 0x7f8dae595730>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module 'gast' has no attribute 'Index'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
[2023-02-13 22:27:08,003][tensorflow][WARNING] - AutoGraph could not transform <bound method Processor.mask of <tensorflow.python.eager.function.TfMethodTarget object at 0x7f85eb177970>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module 'gast' has no attribute 'Index'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
[2023-02-13 22:27:08,930][tensorflow][WARNING] - Model was constructed with shape (None, 65, 1) for input KerasTensor(type_spec=TensorSpec(shape=(None, 65, 1), dtype=tf.float32, name='input_2'), name='input_2', description="created by layer 'input_2'"), but it was called on an input with incompatible shape (None, 65, 65).
[2023-02-13 22:27:11,745][tensorflow][WARNING] - AutoGraph could not transform <bound method CELoss.call of <losses.cross_entropy_loss_2.CELoss object at 0x7f8f8d3f2ee0>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module 'gast' has no attribute 'Index'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
[2023-02-13 22:27:21,835][tensorflow][WARNING] - Model was constructed with shape (None, 65, 1) for input KerasTensor(type_spec=TensorSpec(shape=(None, 65, 1), dtype=tf.float32, name='input_2'), name='input_2', description="created by layer 'input_2'"), but it was called on an input with incompatible shape (None, 65, 65).
[2023-02-13 22:46:53,765][tensorflow][WARNING] - Model was constructed with shape (None, 65, 1) for input KerasTensor(type_spec=TensorSpec(shape=(None, 65, 1), dtype=tf.float32, name='input_2'), name='input_2', description="created by layer 'input_2'"), but it was called on an input with incompatible shape (None, 65, 65).
[2023-02-13 23:07:18,576][tensorflow][WARNING] - Skipping full serialization of Keras layer <tensorflow.python.keras.layers.core.Activation object at 0x7f8dae4927c0>, because it is not built.
[2023-02-13 23:07:19,164][tensorflow][WARNING] - Skipping full serialization of Keras layer <tensorflow.python.keras.layers.pooling.AveragePooling1D object at 0x7f8dae4fe520>, because it is not built.
[2023-02-13 23:07:54,704][absl][WARNING] - Found untraced functions such as activation_layer_call_fn, activation_layer_call_and_return_conditional_losses, dense_layer_call_fn, dense_layer_call_and_return_conditional_losses, transformer_encoder_layer_call_fn while saving (showing 5 of 2530). These functions will not be directly callable after loading.
[2023-02-13 23:07:55,524][absl][WARNING] - Found untraced functions such as activation_layer_call_fn, activation_layer_call_and_return_conditional_losses, dense_layer_call_fn, dense_layer_call_and_return_conditional_losses, transformer_encoder_layer_call_fn while saving (showing 5 of 2530). These functions will not be directly callable after loading.
[2023-02-13 23:08:39,656][tensorflow][INFO] - Assets written to: /home/moshelaufer/PycharmProjects/results/checkpoint/synth_autoencoder_noy/9/assets
