[2023-02-13 22:29:59,113][tensorflow][WARNING] - AutoGraph could not transform <bound method GroupNormalization.call of <tensorflow_addons.layers.normalizations.GroupNormalization object at 0x7fb031455070>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module 'gast' has no attribute 'Index'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
[2023-02-13 22:30:06,081][tensorflow][WARNING] - AutoGraph could not transform <bound method Processor.mask of <tensorflow.python.eager.function.TfMethodTarget object at 0x7fb030afc100>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module 'gast' has no attribute 'Index'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
[2023-02-13 22:30:06,963][tensorflow][WARNING] - Model was constructed with shape (None, 65, 1) for input KerasTensor(type_spec=TensorSpec(shape=(None, 65, 1), dtype=tf.float32, name='input_2'), name='input_2', description="created by layer 'input_2'"), but it was called on an input with incompatible shape (None, 65, 65).
[2023-02-13 22:30:09,743][tensorflow][WARNING] - AutoGraph could not transform <bound method CELoss.call of <losses.cross_entropy_loss_2.CELoss object at 0x7fb2140d4f70>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module 'gast' has no attribute 'Index'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
[2023-02-13 22:30:19,708][tensorflow][WARNING] - Model was constructed with shape (None, 65, 1) for input KerasTensor(type_spec=TensorSpec(shape=(None, 65, 1), dtype=tf.float32, name='input_2'), name='input_2', description="created by layer 'input_2'"), but it was called on an input with incompatible shape (None, 65, 65).
[2023-02-13 22:50:14,152][tensorflow][WARNING] - Model was constructed with shape (None, 65, 1) for input KerasTensor(type_spec=TensorSpec(shape=(None, 65, 1), dtype=tf.float32, name='input_2'), name='input_2', description="created by layer 'input_2'"), but it was called on an input with incompatible shape (None, 65, 65).
[2023-02-13 23:11:05,214][tensorflow][WARNING] - Skipping full serialization of Keras layer <tensorflow.python.keras.layers.core.Activation object at 0x7fb0314ec220>, because it is not built.
[2023-02-13 23:11:05,805][tensorflow][WARNING] - Skipping full serialization of Keras layer <tensorflow.python.keras.layers.pooling.AveragePooling1D object at 0x7fb03134d520>, because it is not built.
[2023-02-13 23:11:41,346][absl][WARNING] - Found untraced functions such as activation_layer_call_and_return_conditional_losses, activation_layer_call_fn, dense_layer_call_and_return_conditional_losses, dense_layer_call_fn, transformer_encoder_layer_call_and_return_conditional_losses while saving (showing 5 of 2530). These functions will not be directly callable after loading.
[2023-02-13 23:11:42,129][absl][WARNING] - Found untraced functions such as activation_layer_call_and_return_conditional_losses, activation_layer_call_fn, dense_layer_call_and_return_conditional_losses, dense_layer_call_fn, transformer_encoder_layer_call_and_return_conditional_losses while saving (showing 5 of 2530). These functions will not be directly callable after loading.
[2023-02-13 23:12:33,053][tensorflow][INFO] - Assets written to: /home/moshelaufer/PycharmProjects/results/checkpoint/synth_autoencoder_shlomi/2/assets
